### ISSUE TITLE
For students with eighth period admin, all /eighth pages highlight the Signup instead of Admin navbar entry

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#101]

**Comment by ethanal** [comment]
Hmm looks like it works for me
![screen shot 2015-05-15 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/941041/7658447/51c6d2b2-fb08-11e4-9894-b197574f5c41.png)

**Comment by ethanal** [comment]
Have you pulled recently? I think there were changes to the context processor in the last few pushes.

**Comment by jwoglom** [comment]
I saw this occur in production, which isn't currently up to date with
recent development. In my sandbox I am not seeing this issue, so I think it
can be safely closed for now.
