### ISSUE TITLE
Pylint 2.6.0 fails on the Ion codebase

### ISSUE THREAD

**Issue by DasBundesland** [tjcsl/ion#1027]
## Steps to reproduce
1. Run the latest version of `pylint` on the codebase (see [https://github.com/DasBundesland/ion/runs/1019595577](https://github.com/DasBundesland/ion/runs/1019595577))

## Expected behavior
The pylint run should be successful as this run is on a complete copy of `tjcsl/master` without any changes. 

## Actual behavior
The pylint run fails because v2.6.0 adds the `raise-missing-from` and `super-with-arguments` checks, which invalidates a bunch of existing Ion code (see [http://pylint.pycqa.org/en/latest/whatsnew/changelog.html](http://pylint.pycqa.org/en/latest/whatsnew/changelog.html)).

**Comment by anonymoose2** [comment]
For reference, Ion used to support Python 2, and this may be why there are places that don't use the new (in Python 3) `super()`.

**Comment by Laur04** [comment]
@anonymoose2 would best practice be to update the code for compliance or just disable those checks?

**Comment by anonymoose2** [comment]
I haven't reviewed the code carefully to see exactly what Pylint is complaining about in most of these cases, but I would say probably update for compliance.

Generally, I disable the checks if it looks like Pylint is just being picky. In this case, however, it looks like the complaints are actually well-founded -- we probably *should* be using new-style `super()` calls, and re-raising with `from` adds potentially helpful information to the traceback. It's really just a judgment call.

**Comment by Laur04** [comment]
Okay, that makes reasonable sense. I’ll make the changes that it’s complaining about.
