### ISSUE TITLE
Going to login page URL when logged in should redirect to index page or next= location

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#104]
When a user is logged in, going to a /login?next= URL should redirect to the next location, defaulting to the index page if that is not defined, instead of showing the login page.

**Comment by ethanal** [comment]
I think that might cause a redirect loop. If a page requires a permission
that a user doesn't have (e.g. attendance taker) then django redirects to
the login page with the next parameter set to the page originally accessed.

**Comment by ethanal** [comment]
I think this is necessary for Django permissions decorators to work right.
