### ISSUE TITLE
Feedback when pressing button for forward email

### ISSUE THREAD

**Issue by etnguyen03** [tjcsl/ion#1040]
## Feature description
Currently, there is no feedback for the "forward email" button. As it is pressed, there is no message that says "processing."

## Rationale for adding feature
Many people are spamming the button until it works or fails, which is bad.

## Suggested implementation(s) (if applicable)
- Possibly handle it similarly to Ion's login button? (where the button swaps with a spinner)
- Disable the button while Ion is waiting a response

**Comment by anonymoose2** [comment]
Another option: Use `Messenger` to show a "Processing..." dialog (with no `hideAfter` timeout and `showCloseButton: false`, then switch it to "Success" or "Failed" when it finishes. Sort of like [this](https://github.com/tjcsl/director4/blob/51d91ffdeadd98e8de631744db801a0e964df3ab/manager/director/static/js/site-status-notifier.js).
