### ISSUE TITLE
Allow authorization without use of a Kerberos account (only with LDAP simple bind)

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#105]
The eighthoffice account formerly did not exist in Kerberos, making login impossible in Ion. In Iodine, login only required using an LDAP simple bind for users such as eighthoffice. While adding users to Kerberos is an option, allowing authorization for specific users without it allows them to login when our Kerberos infrastructure is down and we should consider adding this functionality back in the future.

**Comment by pefoley2** [comment]
So, should this be an alternative to master password that tries a simple bind w/ the supplied creds?
I assume we'd want a hard-coded list of valid usernames for this?

**Comment by jwoglom** [comment]
This was to allow the eighth period office user, before it was in Kerberos,
to log in. Don't believe there are any other non-krb accounts that I know
of, so this is on hold for now.
