### ISSUE TITLE
Disable checkboxes in eighth admin activity edit page

### ISSUE THREAD

**Issue by Laur04** [tjcsl/ion#1070]
## Steps to reproduce
1. Navigate to https://localhost:8080/eighth/admin/activities/edit/1 (after adding an activity in your dev environment)
2. Uncheck the "restricted" box
3. You are able to check the Freshman Allowed, Sophomores Allowed, Juniors Allowed, Seniors Allowed boxes

## Expected behavior
When the "restricted" box is unchecked, the above boxes should be both grayed out (readonly) and have `disabled=true`

## Actual behavior
The Freshman, Sophomore and Junior boxed are only grayed out; the Senior box doesn't change at all.

**Comment by KrishnanS2006** [comment]
I will (attempt) to fix this issue

**Comment by KrishnanS2006** [comment]
When I try to reproduce the issue, none of the boxes are grayed out. Do I need any users/prior restrictions before unchecking?

**Comment by Laur04** [comment]
You shouldn't need anything like that. If you try clicking the checkboxes, you should see that the Freshmen, Sophomore and Junior boxes have a gray check, while the Senior checkbox turns orange. If you look at the source, you will see that the first three have `disabled=True` while the Senior box doesn't.
