### ISSUE TITLE
Senior email forward page should show "end of the school year" instead of "conclusion of the summer"

### ISSUE THREAD

**Issue by etnguyen03** [tjcsl/ion#1124]
This issue is being created for training purposes. PLEASE DO NOT SUBMIT A PULL REQUEST FOR THIS ISSUE UNLESS YOU ARE EXPLICITLY AUTHORIZED TO DO SO.

## Steps to reproduce
1. Go to the senior email forwarding page (`/emailfwd/senior`)
2. Look at the output

## Expected behavior
The page should reference "at the conclusion of the school year," because seniors won't be able to sign in to Ion after approximately mid June.

## Actual behavior
The page shows "at the end of the summer".

**Comment by oz9un** [comment]
Hi @etnguyen03,

I can send a pull request for this issue if I understood it correctly.

What you mean is, instead of that paragraph:
```diff
- <p><b>By the end of the summer after graduation, 
your TJ Network Account will be deleted.</b> However, you can configure messages sent to your TJ Email address, <b>{{ request.user.tj_email }}</b>, to forward to another address (such as your university email or a personal email). You will not be able to log into Webmail. Once set at the conclusion of the summer, this address can't be changed.</p>
    <p>Do not operate under the assumption that your mail will continue to forward for extended periods of time. You should attempt to transition away from using your TJ email over the next few years.</p>
    <p>Enter the email address to forward messages sent to <b>{{ request.user.tj_email }}</b> after your TJ Network Account is deleted:</p>
```
This paragraph:

 ```diff
+ <p><b>At the conclusion of the school year,
 your TJ Network Account will be deleted.</b> However, you can configure messages sent to your TJ Email address, <b>{{ request.user.tj_email }}</b>, to forward to another address (such as your university email or a personal email). You will not be able to log into Webmail. Once set at the conclusion of the summer, this address can't be changed.</p>
    <p>Do not operate under the assumption that your mail will continue to forward for extended periods of time. You should attempt to transition away from using your TJ email over the next few years.</p>
    <p>Enter the email address to forward messages sent to <b>{{ request.user.tj_email }}</b> after your TJ Network Account is deleted:</p>
```

Right?

**Comment by etnguyen03** [comment]
Hello @oz9un, thank you for your interest in contributing to Ion. Ion is an internal application that we have made open source. Due to program constraints, we are unable to accept pull requests from persons not part of the TJ community.

**Comment by oz9un** [comment]
Oh I see, thanks for your response @etnguyen03!. As far as I can review, you have many repositories that I am interested in.

I would love to contribute your projects in fields of cybersecurity, web development if that is possible. I do not know if there is any way to get into TJ community... I am kind of newbie to open source contribution.
