### ISSUE TITLE
Events page shows the user who approved and created even if it is None

### ISSUE THREAD

**Issue by etnguyen03** [tjcsl/ion#1127]
This issue is being created for training purposes. PLEASE DO NOT SUBMIT A PULL REQUEST FOR THIS ISSUE UNLESS YOU ARE EXPLICITLY AUTHORIZED TO DO SO.

## Steps to reproduce
1. Add an event(s) with [this script](https://github.com/tjcsl/ion/blob/master/intranet/apps/events/management/commands/import_sports.py) or the function it calls
2. Look at `/events`, both as an admin and not as one

## Expected behavior
See the screenshot below (in Actual behavior). If there is no person who created the activity, then the activity should not show who created the activity (because there is no person who did). ([see this line](https://github.com/tjcsl/ion/blob/158881310895fb5bac4525c2bc6a878677846f73/intranet/templates/events/event.html#L54).)

Additionally, as an eighth admin, "approved by" probably shouldn't show if there is no approver. See [this](https://github.com/tjcsl/ion/blob/158881310895fb5bac4525c2bc6a878677846f73/intranet/templates/events/event.html#L90).

## Actual behavior
![image](https://user-images.githubusercontent.com/3579871/115160351-c27c5000-a065-11eb-98a1-d69562ad139a.png)

**Comment by ramnreddy15** [comment]
I am working on this issue.

**Comment by Laur04** [comment]
Please also change “stops” to “stop” in your commit message. Commit messages always use the imperative tense.
