### ISSUE TITLE
Create a management command to export senior email forwards

### ISSUE THREAD

**Issue by etnguyen03** [tjcsl/ion#1152]
## Feature description
Create a [Django management command](https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/) to export senior email forwards in a format compatible with Postfix's alias file, like this:

```
{{ CSL username }}:\t\t{{ new email }}
```

## Rationale for adding feature
Last year I had to pull it out of the ORM manually and that was a pain.

## Suggested implementation(s) (if applicable)
Perhaps have the command just output to `stdout` then we can pipe to a file?

**Comment by Edald123** [comment]
Hi! I'm new on this, may I contribute to this issue?
If so, can you give more detail on the issue? Thank you!

**Comment by etnguyen03** [comment]
> Hi! I'm new on this, may I contribute to this issue?
> If so, can you give more detail on the issue? Thank you!

Hello @Edald123, thank you for your interest in contributing to Ion. Ion is an internal application that we have made open source. Due to program constraints, we are unable to accept pull requests from persons not part of the TJ community.

**Comment by Edald123** [comment]
I totally understand, best regards and wish you a lot of success on your project!
