### ISSUE TITLE
Fix positioning of user dropdown in mobile view

### ISSUE THREAD

**Issue by ethanal** [tjcsl/ion#12]

**Comment by ethanal** [comment]
Seems to be fine now.

**Comment by ethanal** [comment]
![screen shot 2015-04-06 at 3 26 03 am](https://cloud.githubusercontent.com/assets/941041/7001721/ae6f117a-dc0c-11e4-9890-ccea9282b6c4.png)
Should be centered

**Comment by jwoglom** [comment]
fixed, i believe
