### ISSUE TITLE
Change "Profile Edit" form for users of non-student type

### ISSUE THREAD

**Issue by Rushilwiz** [tjcsl/ion#1364]
8PO has issues editing user info for staff members with blank fields for `FCPS Student ID` and `Graduation Year`, and while this isn't a huge issue, might be something easy to start with.

## Steps to reproduce
1. Attempt to edit a staff user through the GUI

## Expected behavior
Extra fields should not be required or possibly rendered either.

## Actual behavior
You are unable to edit other fields without populating the empty ones.

**Comment by abhishinde24** [comment]
can i work on this issue?
