### ISSUE TITLE
Change 48-hour presign time

### ISSUE THREAD

**Issue by Rushilwiz** [tjcsl/ion#1404]
## Feature description
~~Move 48-hour presign to just after noon (12:05AM) instead of at midnight.~~
Create a setting field to allow 48-hour presign time to be set differently than midnight.

## Rationale for adding feature
Students should not be awake at midnight signing up, this increases fairness in eighths.

**Comment by alanzhu0** [comment]
Assuming this meant 12:05pm...what do you think about something like 8:00, maybe 8:20am? It would help lighten the load on Ion and most people should be awake by then.

**Comment by KrishnanS2006** [comment]
I'd suggest 2:15 pm - it makes the most sense since it's exactly 48 hours before 8A the next day, but there are concerns about ion traffic since it's right before 8th periods.

**Comment by alanzhu0** [comment]
I don’t think that would be the best time due to the traffic you mentioned - the 8th glance page is designed to limit large database queries. Also, it could encourage people to be signing up during class or during passing period which shouldn’t be something that they should have to do to sign up.

**Comment by Rushilwiz** [comment]
Right, I had a long think about what would be most practical. Because students always line up to be able to signup for 48-hour presigns, and so it can't be at the beginning of a period. 12:05 or 12:00 makes sense because that's when we break for lunch, but this feature should be implemented with the opening time as a setting, not a hardcoded value.

**Comment by Rushilwiz** [comment]
Updated the issue to be more specific.

**Comment by selsayed25** [comment]
Joining in the convo. I think a time like between when TJ doors open (7:45 AM) to around 8:30ish AM would be an ideal time to not just allow students to sign up for their favorite activities, but also handles the absurd load of students constantly trying to sign up at the exact same time. I think @alanzhu0 time range can work in this situation.

**Comment by alanzhu0** [comment]
@Rushilwiz do you want to leave this for the understudies or do you want it to be done soon? If the latter, I can do it or Kedar mentioned he'd be interested in it.

**Comment by Rushilwiz** [comment]
Good work kedar! #1419 closes this.
