### ISSUE TITLE
Month schedule view broken

### ISSUE THREAD

**Issue by Rushilwiz** [tjcsl/ion#1410]
## Steps to reproduce
1. Click "Month" on schedule view

## Expected behavior
Show the entire month?

## Actual behavior
![image](https://user-images.githubusercontent.com/15521024/193160183-015968df-bc34-4b5c-8855-d238cc1d39bd.png)

Probably the problem:
![image](https://user-images.githubusercontent.com/15521024/193160148-70b39115-8f7b-4a71-9200-315bfa86b66b.png)

**Comment by alanzhu0** [comment]
@Rushilwiz please see Mattermost

**Comment by alanzhu0** [comment]
Resolved, can someone close?
