### ISSUE TITLE
Issue trying to set up a dev environment

### ISSUE THREAD

**Issue by kmalki** [tjcsl/ion#1425]
## Steps to reproduce
1. Trying to build and launch the docker part (gap in how to set up the dev environment in the SETUP.md).

## Expected behavior
Database, server and interface up

## Actual behavior
Database container :
```
LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
```
Container intranet output :
```
django.db.utils.OperationalError: connection to server on socket "/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

**Comment by Rushilwiz** [comment]
Did your `docker-compose up` work correctly? What's the output of the command if you run it without `-d`?

**Comment by kmalki** [comment]
No it didn't work for the intranet container, looping on this issue mentioned earlier.

**Comment by kmalki** [comment]
No one ?

**Comment by alanzhu0** [comment]
Thank you for the issue report; we are actively working on a fix.
