### ISSUE TITLE
Fix bus page CSS

### ISSUE THREAD

**Issue by ramnreddy15** [tjcsl/ion#1453]
## Steps to reproduce
1. Go to [Bus Page](https://ion.tjhsst.edu/bus)

## Expected behavior

- "Prince William" should be abbreviated to "PW" or not exist
- Text on the "On Time" and "Arrived" headers should be visible

## Actual behavior

- "Prince William" overflows and isn't visible
- Text on the headers isn't visible because of the neon colors used as the background

I would recommend changing the CSS for the headers to the colors used in [Schedule](https://ion.tjhsst.edu/schedule) for consistency and easy readability.

**Comment by alanzhu0** [comment]
@Rushilwiz @shahsalonik Can an Ion admin delete the "Prince William" bus?
@ramnreddy15 Could you clarify what you mean by the headers?

**Comment by shahsalonik** [comment]
@alanzhu0 We can delete it, but I want to double-check to see if it's being used. @Rushilwiz Do you have a better idea about why there's just a bus called "Prince William"?

**Comment by ramnreddy15** [comment]
@alanzhu0 I added some more detail; I hope it makes more sense

**Comment by alanzhu0** [comment]
@ramnreddy15 if you are looking for the morning view, you can access that at any time [here](https://ion.tjhsst.edu/bus/morning).

**Comment by ramnreddy15** [comment]
@alanzhu0 The text I circled is basically not visible: 
![image](https://user-images.githubusercontent.com/69733662/200419134-a4a23f63-a8fc-42fd-bd37-41319d67825c.png)

You can easily fix this with changing the green, blue, red css to the same green, blue, red colors as the schedule. 
![image](https://user-images.githubusercontent.com/69733662/200419455-220e8722-83aa-45c9-8031-0ab8027e0416.png)

This makes it consistent and increase readability.

**Comment by Rushilwiz** [comment]
Sorry folks! I missed this PR, the "Prince William" bus is an old artifact, just deleted. 

Make sure to keep these internal convos on mmost!
