### ISSUE TITLE
Bus: Cancelled Buses

### ISSUE THREAD

**Issue by selsayed25** [tjcsl/ion#1455]
## Topic of discussion
The PA at the end of the school day tells everyone which bus they should ride on if their bus is cancelled (i.e JT-305 is cancelled, all riders go on JT-302). We should try to find a more effective way to get the news of a bus cancellation to the student better.

## Proposed options/solutions
- Mine and @KrishnanS2006's proposal: On the bus app, the admin would set which buses are cancelled, and what is the alternative bus(es). If a student is on a bus that is cancelled, the bus bar would say "[YOUR BUS] is cancelled. Please ride [ALTERNATIVE BUS]". It would also highlight the alternative bus for the student to find their bus easier.
- @alanzhu0's proposal: The admin would set which buses are cancelled, and what is the alternative bus. Once they set it, this would automatically make an announcement on the dashboard for the cancelled bus. (Correct me Alan if I missed something)

## Personal opinion (if applicable)
In my opinion: I believe that mine and Krishnan's proposal would work best since in the afternoon, Ion redirect you to the bus app, and it is much more effective to have the student take a glance at the app and see which and where their bus is.

**Comment by selsayed25** [comment]
**Extra Info for both proposals**: Please also note that there can be TWO alternative buses, one for a different stop. We should add a feature on the bus admin page to allow the admin to add two different alternative buses for the appropriate stop. This however means that we need a list of bus stops for each bus (to implement to the API), and have the student choose which stop they regularly go to.

**Comment by alanzhu0** [comment]
@selsayed25 for my proposal, it would've been more like linking an announcement and using the existing model to display information on the bus page, but I do agree your idea is better. 

For the comment regarding multiple buses, I think the easiest way to do this would be just to allow bus admins to enter the information into a bus announcement and display that text in this situation - in other words, just an announcement attached to a particular bus. This allows for highly specific announcements that we wouldn't be able to integrate well with the backend. 

Another note: I think it would also be necessary for *all* delayed bus announcements to be displayed, maybe in a sidebar, on signages and for people who have not registered their bus route.

**Comment by selsayed25** [comment]
> @selsayed25 for my proposal, it would've been more like linking an announcement and using the existing model to display information on the bus page, but I do agree your idea is better.

Ah that makes more sense!

> For the comment regarding multiple buses, I think the easiest way to do this would be just to allow bus admins to enter the information into a bus announcement and display that text in this situation - in other words, just an announcement attached to a particular bus. This allows for highly specific announcements that we wouldn't be able to integrate well with the backend.

This could be implemented in the bus app itself. We could have the announcement displayed somewhere in the bus app to notify the student on where their bus is.

> Another note: I think it would also be necessary for all delayed bus announcements to be displayed, maybe in a sidebar, on signages and for people who have not registered their bus route.

Similarly, just have the announcement be on the bus app, but below the status that states "Time until departure". We could push the bar up and display both the late buses, and alternatives (including the stops that the admin must place).

**Comment by KrishnanS2006** [comment]
I also like @alanzhu0's idea of using an announcement template for this - it would make it straightforward for everyone, not just those who have their bus set. However, I really don't like the idea of it being on the announcements page, especially with the bus redirect as mentioned by @selsayed25. I think along with the announcement at the top of the bus page, the personalized statement ("[bus] is on time") being changed as described originally by @selsayed25 is the best solution. Any ideas?
