### ISSUE TITLE
Polls: Support "Standard Other" question type

### ISSUE THREAD

**Issue by alanzhu0** [tjcsl/ion#1525]
## Feature description
- Question type that allows users to select an answer (like in `Standard`) but also adds an "Other" option where users can write-in a response.

Example:
What is your favorite fruit?
- Apples
- Oranges
- Bananas
- Other: _______________ (textbox)

## Rationale for adding feature
- Standard other (STO) is already a question type in the Polls app. However, it hasn't been implemented.
- It's useful

## Suggested implementation(s) (if applicable)
- Look at implementations of the Standard and Short Response question types.

**Comment by avnithv** [comment]
Hi, can I take this issue?

**Comment by alanzhu0** [comment]
Yes, go for it!
