### ISSUE TITLE
Prevent 502 Gateway Timeouts on large operations

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#155]

**Comment by jwoglom** [comment]
I have added:
```
proxy_read_timeout   5m;
proxy_connect_timeout   2m;
```
to the nginx config but this does not appear to have helped.

**Comment by ethanal** [comment]
Have you tried bulk creates for stuff like signing up 2000 students? https://docs.djangoproject.com/en/dev/ref/models/querysets/#bulk-create

**Comment by pefoley2** [comment]
Bulk operations definitely help a lot.
You could probably just use bulk operations unconditionally for queries that could operate on a lot of objects, there shouldn't be much overhead for just one or two.

**Comment by Laur04** [comment]
I believe Celery resolves this...reopen if I'm wrong.
