### ISSUE TITLE
Complete change from 48 hour pre-signup to 2 day custom time

### ISSUE THREAD

**Issue by alanzhu0** [tjcsl/ion#1577]
Commit https://github.com/tjcsl/ion/commit/bc1c21252c904fd25508d3da24f8563bac27c8b8 added the feature for a custom 2 day presign time, changing it from the old 48 hour restriction.

However, the 48 hour text (not logic) still exists in the Ion codebase. Those need to be replaced with the 2 day text.

**Comment by alanzhu0** [comment]
@ksquaring do you want to do this?

**Comment by shrysjain** [comment]
Hey, can I try resolving this one?

**Comment by alanzhu0** [comment]
Yes!

**Comment by shrysjain** [comment]
@alanzhu0 ready for review :)
