### ISSUE TITLE
Remove pinned announcements in archive view

### ISSUE THREAD

**Issue by alanzhu0** [tjcsl/ion#1604]
When viewing the announcement archive (https://ion.tjhsst.edu/announcements/archive), pinned announcements appear at the beginning of the list. However, since there are so many pinned announcements, they take up many pages of the view. Announcements should instead be ordered solely based on date posted in the archive view.

- It would also be nice to have a way to move between multiple pages quickly. Perhaps buttons with the page numbers, similar to how Django admin does it.

**Comment by JasonGrace2282** [comment]
Can I try this one?

**Comment by alanzhu0** [comment]
Sure! Let me know if you have questions.
