### ISSUE TITLE
Implement Ion bus game

### ISSUE THREAD

**Issue by ksquaring** [tjcsl/ion#1653]
## Feature description
Implement the bus game feature in the bus app. Users will access this by clicking on an empty bus spot then clicking skrt skrt. Feel free to make whatever game you want; just have it thematically use a bus somehow. Potential ideas could include some sort of crossy road themed game.

## Rationale for adding feature
Makes Ion more awesome.

**Comment by Catelyn-Dao** [comment]
Hey- can you assign this one to @shrysjain and I? We'd like to give this one a shot together, thanks!

**Comment by krishnans2006** [comment]
@shrysjain could you post a comment here so we can assign you to the issue?

**Comment by shrysjain** [comment]
@krishnans2006 oops, here 👍

**Comment by krishnans2006** [comment]
A few things to take a look at that may or may not be helpful:
- `static/css/bus.scss` lines 227-253
- `static/js/bus-afternoon.js` lines 471-598
- `static/js/busdriver.js`
- `static/img/bus_top.png`

Good luck!
