### ISSUE TITLE
UI error when taking attendance for a past eighth period 

### ISSUE THREAD

**Issue by NotFish232** [tjcsl/ion#1660]
## Steps to reproduce
1. Try to take attendance for an eighth period that has happened on a previous day

## Expected behavior
Date shows up properly, with the input field date matching the header date

## Actual behavior
Input field and actual date differ
![Screenshot from 2024-04-09 08-42-38](https://github.com/tjcsl/ion/assets/99909994/b8660b50-101b-44f1-bc3d-99378f545d23)

**Comment by hstievat** [comment]
oops sorry I forgot to ask... can you assign this issue to me?
