### ISSUE TITLE
Checking for IDs in selectize makes searching very slow

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#168]

**Comment by pefoley2** [comment]
Is this still an issue?

**Comment by jwoglom** [comment]
I forget if this had to do with student id numbers or activity id numbers, but I think it was activity id numbers because selectize was used with those in a number of places. I think the problem was some javascript so that if you entered a number (e.g. 40) in the selectize box, the top result would be the activity with ID 40 rather than maybe 140 being the top result because the entry name was "Activity Name (140)" and it contained the "40" substring. this code probably got removed because we told the eighth office to not enter in the ID number and hit enter, and instead look through the list to find the right activity with that id. @ovkulkarni

**Comment by theo-o** [comment]
Haven't received any complaints regarding this from Eighth Office. Closing.
