### ISSUE TITLE
Fix portrait orientation signage bus CSS

### ISSUE THREAD

**Issue by alanzhu0** [tjcsl/ion#1680]
Fix the signage bus board CSS for portrait orientation signages. It is covering part of the bus map. Do not change (or change only minimally) the CSS for horizontal signages. This may be hard to test due to screen sizes.![image](https://github.com/tjcsl/ion/assets/90356452/dd57e1f0-2b03-4016-8e60-379e3f81fac2)

**Comment by DhanvinG** [comment]
Can I take this?
