### ISSUE TITLE
Make Eighth Activities Searchable By Description

### ISSUE THREAD

**Issue by NotFish232** [tjcsl/ion#1683]
## Feature description
When choosing an eighth signup, add the ability to search for activity by text in its description

## Rationale for adding feature
Searching by keywords is helpful, especially for special events like tjSTAR where people might want to search for names or project categories

**Comment by DhanvinG** [comment]
Hi, could I also have this issue assigned?

**Comment by NotFish232** [comment]
Sure! Let me know if you need any help
