### ISSUE TITLE
Individual User Sticky to Activity

### ISSUE THREAD

**Issue by alanzhu0** [tjcsl/ion#1719]
## Feature description
- Allow individual students to be stickied to an activity. Currently, only entire activities or scheduled instances of an activity can be marked as sticky. This feature would allow 8PO to specify individual students that cannot unsignup from an activity, while all other students can.

## Rationale for adding feature
- Requested by Math/CS Dept for tutoring sessions.

## Suggested implementation(s) (if applicable)
- Currently, the sticky logic is binded only to an `EighthScheduledActivity`. There could be a field added to `EighthScheduledActivity` called `sticky_students` or similar. `EighthSignup` may need to have a sticky attribute. I haven't looked at the code yet so these attributes might already be in place.

https://ion.tjhsst.edu/eighth/admin/scheduling/schedule?activity=925
The schedule activity screen would be a good place to add this:
![image](https://github.com/user-attachments/assets/e0d4813e-a04f-44e5-b223-7537661c61eb)
There could be a dropdown field added for stickied students (similar to the sponsor field).

**Comment by shrysjain** [comment]
Club announcements features left to add:
- Archive
- Search
- Restrict subscriptions for restricted activities to only those on the authorized list
PR on GitHub

**Comment by JasonGrace2282** [comment]
@alanzhu0 can you assign me to the issue?

**Comment by alanzhu0** [comment]
@shrysjain this goes in #1647
