### ISSUE TITLE
Investigate use of a CSS preprocessor (SASS?)

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#209]
http://django-pipeline.readthedocs.org/en/latest/compilers.html

**Comment by tcyrus** [comment]
The 3 CSS preprocessors stated on the django-pipeline docs are [LESS](http://lesscss.org/), [SASS](http://sass-lang.com/), and [Stylus](http://learnboost.github.com/stylus/)

**Comment by pefoley2** [comment]
Alright, I've got most of the infrastructure in place, but somebody needs to go through and convert the rest of the css files to use django-pipeline.

**Comment by tcyrus** [comment]
Did we decide on a CSS Preprocessor

**Comment by pefoley2** [comment]
Yeah, I googled around a bit, and SASS looked like the best choice.

**Comment by tcyrus** [comment]
I can get started on converting the CSS to SCSS

**Comment by pefoley2** [comment]
The priority is getting the existing css to work w/ django-pipeline.
Let's do that before we work on actually taking advantage of scss.

**Comment by pefoley2** [comment]
I'd just work on the pipeline branch, tbh.
Just focus on converting everything to use {% stylesheet %} and adding the css stuff to the config.

**Comment by jwoglom** [comment]
all in the pipeline branch please

**Comment by pefoley2** [comment]
That's what I said...
