### ISSUE TITLE
Trying to access M drive with invalid credentials doesn't show error clearly

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#217]
Instead, I get redirected to the home files page, and then have to click on M again to get the error, which is not very obvious, being in the corner of the screen.

**Comment by pefoley2** [comment]
This also applies to R drive and Windows root

**Comment by jwoglom** [comment]
This should be, and on my end is, redirecting to the authentication page. I would imagine this behavior is due to your odd account status.
