### ISSUE TITLE
Have maximum upload/download size be configurable and centralized

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#223]
Move the magic constant from the filecenter code to the config file.

**Comment by jwoglom** [comment]
This seems unnecessary, as these options will very rarely be changed.

**Comment by pefoley2** [comment]
Perhaps, but having identical magic constants in different code files, instead of in one config file is bad practice.

**Comment by jwoglom** [comment]
This may be changed in the future, but right now this is not an issue we are currently facing in our environment.
