### ISSUE TITLE
Accessing paths outside of afs homedir only works with afs, not csl

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#224]
Admins should be able to access paths outside of their homedir using files/csl, but the parent directory doesn't show up, and they can't manually modify the url to a parent directory without getting an access denied error. files/afs on the other hand, works fine.

**Comment by jwoglom** [comment]
The CSL and AFS entries are identical except for the default folder option, which is "/afs/csl" for AFS and the default home directory for CSL. If you are an admin, the logic of the code says that you should be able to do this. This issue likely occurred in earlier code, which has been updated to do this properly.
