### ISSUE TITLE
Browsing to an non-existant file in filecenter causes a 500 instead of displaying an error

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#226]
e.g. https://ion.tjhsst.edu/files/csl?file=/afs/csl.tjhsst.edu/students/2013/pfoley/idontexist
on the other hand,
https://ion.tjhsst.edu/files/csl?dir=/afs/csl.tjhsst.edu/students/2013/pfoley/idontexist
shows a "does not exist" error properly.
(file= vs dir=)
I wasn't able to find a backtrace in the logs so I'm not sure exactly where it's dying.

**Comment by jwoglom** [comment]
This was likely dying on the "sftp.stat()" command. Every instance of this now has a try/except block around it, which shows an error message popup instead of 500ing.
