### ISSUE TITLE
Activities with special characters display incorrectly

### ISSUE THREAD

**Issue by gengkev** [tjcsl/ion#232]
Steps to reproduce:

* signup for an activity with a special character (e.g. `Codi's Hats`)
* note that before refreshing, the activity selector shows the name with HTML entities (e.g. `Codi&#39;s Hats`)

It looks like the problem is in [signup.js](https://github.com/tjcsl/ion/blob/911790f1d0691dfbf36b90dbaac7f867598fe68a/intranet/static/js/eighth/signup.js#L161), where the activity name is simply assigned with `el.text()`. The easiest way to fix it might be to [create a dummy `textarea` to convert the entities](http://stackoverflow.com/a/1395954/689161).

**Comment by jwoglom** [comment]
Thanks for the suggestion -- this is now fixed as of 1c72f25.
