### ISSUE TITLE
Add /api/logout

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#233]
Normal Logout Doesn't Affect the API Session

**Comment by fwilson42** [comment]
This is a feature; your browser will remember credentials for HTTP Basic authentication regardless of what you do in the interface. Closing the browser should make it forget these credentials; there is no way of doing this in the interface.

**Comment by jwoglom** [comment]
You can force a logout by starting a http basic auth session with another
username and password; e.x. https://logout:logout@ion.tjhsst.edu/api
