### ISSUE TITLE
Implement token-based auth for API

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#239]

**Comment by pefoley2** [comment]
Is this resolved with oauth support?

**Comment by sdamashek** [comment]
@pefoley2 I don't believe so; all oauth provides right now is authorization. Unlike the ion API, it doesn't provide any access to ion information. Additionally, making it do so wouldn't be trivial because of the requirement of Kerberos tokens for LDAP.

**Comment by jwoglom** [comment]
Once you're authenticated you should be able to access API as well as
regular page resources. You shouldn't rely on an oauth token for more than
a couple hours because of the LDAP issue, yes. But I think this is solved.

James

**Comment by pefoley2** [comment]
Have we considered falling back to a simple bind for api ldap access?

**Comment by jwoglom** [comment]
This should be happening automatically already.

**Comment by pefoley2** [comment]
What i'm saying is does it error out if your kerb tokens expire? do we want to have oauth allow access even after that?

**Comment by sdamashek** [comment]
What happens if the Kerberos token expires? Even if you renew an OAuth token, that wouldn't renew your Kerberos token, would it?

**Comment by pefoley2** [comment]
Yeah, my point is do we want to support oauth tokens *without* kerberos?
