### ISSUE TITLE
/api/search throws 500

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#273]
When testing out the example API Call, I get this

```
HTTP 500 Internal Server Error
Content-Type: application/json
Vary: Accept
Allow: GET, HEAD, OPTIONS

{
    "details": [
        "Unknown error occurred."
    ]
}
```

**Comment by pefoley2** [comment]
https://ion.tjhsst.edu/api/search/ returns a 404, probably related.

**Comment by pefoley2** [comment]
In other news, the error isn't being logged anywhere, and the error log doesn't have timestamps either.

**Comment by pefoley2** [comment]
Looks like we want to add a logger.debug(response) to https://github.com/tjcsl/ion/blob/master/intranet/apps/api/utils.py#L25
