### ISSUE TITLE
Profile Picture API fails when format parameter is present

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#280]
The format parameter is added to the URL automatically in some circumstances like [here](https://ion.tjhsst.edu/api/profile/489?format=api). This leads to a bad link to the Profile Picture API like this:

[![](https://ion.tjhsst.edu/api/profile/489/picture?format=api)](https://ion.tjhsst.edu/api/profile/489/picture?format=api)

**Comment by jwoglom** [comment]
fixed
