### ISSUE TITLE
Add SVG Intranet Icons

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#281]
The icons located in `ion/intranet/static/img/icons.png` do not have a SVG counterpart.

**Comment by tcyrus** [comment]
Found Corresponding SVG's on Font Awesome:

fa-tachometer
[workaround](http://jsfiddle.net/tcyrus/09dmeL3j/)
fa-calendar
fa-users
fa-check-square-o
fa-folder-open

**Comment by ezwang** [comment]
finished svgs
working on implementing css
