### ISSUE TITLE
schedule activity sponsor changes don't save with cache

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#284]

**Comment by jwoglom** [comment]
This should be fixed.

**Comment by jwoglom** [comment]
Still an issue, when cache is enabled. Mainly happening when changing more than 4 blocks at a time.

**Comment by jwoglom** [comment]
Still an issue, but mitigated due to disabling caching on eighth period.

**Comment by theo-o** [comment]
Haven't seen this.
