### ISSUE TITLE
Choose a license 

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#285]
I'm personally in favor of GPLv2, but we need buy-in from everyone on https://github.com/tjcsl/ion/graphs/contributors
@jwoglom @ethanal @sdamashek @tcyrus @ctrlshiftq @aklaussen @theycallmezeal

**Comment by pefoley2** [comment]
ping! adding @jacobajit

**Comment by jwoglom** [comment]
I officially propose the MIT/BSD license, the same as Iodine.

If anyone has any objections, please comment. Otherwise, I am going to assume everyone is okay with this and will officially add in the license terms in exactly one week.

**Comment by pefoley2** [comment]
I would prefer GPL, but MIT/BSD is acceptable.
Aren't MIT and BSD slightly different though?

**Comment by jwoglom** [comment]
They are worded a bit differently, yes. This is what I meant: http://choosealicense.com/licenses/mit/

**Comment by pefoley2** [comment]
sure, we can just move https://github.com/tjcsl/ion/blob/master/intranet/static/ldap/LICENSE to the top level

**Comment by ethanal** [comment]
My vote is GPL.

**Comment by sdamashek** [comment]
I would prefer GPL.

**Comment by pefoley2** [comment]
@jwoglom will obviously have to agree, but it looks like we've got significant GPL support.

**Comment by jacobajit** [comment]
I prefer MIT for its flexibility, but am fine with either.

**Comment by jwoglom** [comment]
The people who mentioned GPL, 2 or 3?

**Comment by pefoley2** [comment]
I strongly prefer 2, although 3 is acceptable.

**Comment by sdamashek** [comment]
Same here, I would strongly prefer 2.

**Comment by pefoley2** [comment]
Have we actually committed the licence file?

**Comment by jwoglom** [comment]
A license file hasn't been committed. I'm okay with GPL2 if that's what people like.

**Comment by pefoley2** [comment]
I added a licence. If anybody objects, please speak now or forever hold your peace.
