### ISSUE TITLE
Add DigiCert Seal

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#286]
This Seal looks best with the Ion UI
![](https://www.eureprojekte.at/sites/all/themes/ojp/images/digi_seals_seal_page.png)

**Comment by jwoglom** [comment]
It was unofficially decided to not place this on Ion. It looks pretty ugly
and doesn't accomplish any purpose, and digicert is less recognized than
verisign

**Comment by pefoley2** [comment]
Yeah, it looks awful.

**Comment by tcyrus** [comment]
Ok
