### ISSUE TITLE
Check nginx max cookie/header length

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#304]
Eighthoffice kicked out with nginx "400 Bad Request - Request Header Or Cookie Too Large" after unscheduling blocks for activity

**Comment by pefoley2** [comment]
I believe this has been resolved.

**Comment by jwoglom** [comment]
Was something changed in the nginx config?

**Comment by pefoley2** [comment]
Yup,
large_client_header_buffers 4 2k;

**Comment by pefoley2** [comment]
It looks like that's actually less than the default though...

**Comment by theo-o** [comment]
This seems to be resolved.
