### ISSUE TITLE
Use bcc in announcement notification emails

### ISSUE THREAD

**Issue by gengkev** [tjcsl/ion#305]
I've signed up to receive emails when a news item is posted, but the emails don't use bcc; in other words, every time an email is sent, I can see the other 16 people who have opted to receive such emails. This isn't a huge privacy concern since these emails are available on Ion anyway, but it might be prudent to use bcc instead regardless.

Relevant files:
https://github.com/tjcsl/ion/blob/master/intranet/apps/announcements/notifications.py#L132
https://github.com/tjcsl/ion/blob/master/intranet/apps/notifications/emails.py

**Comment by jwoglom** [comment]
Good catch. Already fixed, actually, just not pushed to git yet.

**Comment by gengkev** [comment]
alright, thanks for letting me know!

**Comment by jwoglom** [comment]
Closed as of 00c1855
