### ISSUE TITLE
"15 hourTrue ago"

### ISSUE THREAD

**Issue by fwilson42** [tjcsl/ion#308]
At around 11:10 on a red day, the "Upcoming Eighth Periods" widget will display "Signups close in 1 hours (12:40 p.m.)". This should be "Signups close in 1 hour" instead.

**Comment by jwoglom** [comment]
Should be resolved

**Comment by fwilson42** [comment]
resolved in 0cd1b2584cfe5e85ccaa746bbe468bc03d31cf92

**Comment by fwilson42** [comment]
One of those changes seemed to create another issue:

`return "{} hour{} ago".format(hrs, hrs != 1)`

will make "n hourTrue ago" or "1 hourFalse ago" instead of "hours"/"hour"

**Comment by jwoglom** [comment]
Should actually be correct now
