### ISSUE TITLE
TJ emails still appear in user.emails, and are duplicated on profile page

### ISSUE THREAD

**Issue by fwilson42** [tjcsl/ion#310]

**Comment by jwoglom** [comment]
The eighth office and teachers have said that they always want to see TJ emails, because they should be used for all official communication.

**Comment by pefoley2** [comment]
I think the question is should alternate emails that are the same as official emails show up.

**Comment by tcyrus** [comment]
Note: This was requested by Dr. Gabor

**Comment by jwoglom** [comment]
@pefoley2 What do you mean by "alternate emails that are the same as official emails"

**Comment by pefoley2** [comment]
e.g. official email is foobar@tjhsst.edu, and the user manually adds foobar@tjhsst.edu to their profile as their personal email.

**Comment by jwoglom** [comment]
I don't see why they shouldn't

**Comment by pefoley2** [comment]
Yes, but if they do, what's the point of duplicating the information?
Just have a check to hide the personal email if it == the tj email

**Comment by jwoglom** [comment]
Fixed
