### ISSUE TITLE
Sign Up Button Still Appears after Signups are Locked

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#312]

**Comment by jwoglom** [comment]
Doesn't allow for signing up, though. So it is arguably working as intended

**Comment by jwoglom** [comment]
Clicking the button does show the reason that you can't take attendance -- that the block is locked. The primary reason why this still shows is that it allows for the 8th office/admins to force students into an activity still if they have the permissions.

**Comment by pefoley2** [comment]
Maybe grey it out for people without the necessary permissions to force?
