### ISSUE TITLE
Menu icons

### ISSUE THREAD

**Issue by jacobajit** [tjcsl/ion#333]
https://github.com/tjcsl/ion/blob/master/intranet/static/img/icons.png These pngs look rather pixelated, especially on high-res mobile. Are there svg versions of these?

**Comment by pefoley2** [comment]
I don't think there are, unfortunately.
@ethanal @jwoglom do you know where these came from?

**Comment by jwoglom** [comment]
They come from FontAwesome

**Comment by tcyrus** [comment]
Similar to #281

**Comment by jwoglom** [comment]
If someone could take the vector images from FontAwesome, and re-create the eighth icon (like it is now) as SVG images, that would be awesome.

**Comment by ezwang** [comment]
finished svgs
working on css

**Comment by pefoley2** [comment]
Note that you can do this automatically by putting something like "fixes #333" in the commit message.
https://help.github.com/articles/closing-issues-via-commit-messages/
