### ISSUE TITLE
Don't show 100% icon if activity not full

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#334]

**Comment by tcyrus** [comment]
Current pie icons are generated using

```js
var pieNumber = Math.min(Math.round(roster.count / roster.capacity * 10), 10);
```

in:

ion/intranet/templates/eighth/display.html
ion/intranet/templates/eighth/multi_signup.html
ion/intranet/templates/eighth/signup.html
ion/intranet/templates/eighth/profile_signup.html

**Comment by jwoglom** [comment]
Yes -- already fixed
