### ISSUE TITLE
Disable HTTP OPTIONS requests in API views

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#344]

**Comment by ovkulkarni** [comment]
@jwoglom what was the reasoning behind this?

**Comment by jwoglom** [comment]
Don't recall exactly why but I imagine it's not important.

Might've been something relating to this: https://dbader.org/blog/django-rest-framework-options-response

**Comment by theo-o** [comment]
Given that Ion is open-source and its code is publicly available, leaking docstrings does not appear to be a serious issue.  Closing.
