### ISSUE TITLE
Increase redis priority of session cache

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#351]
If the redis cache fills up, we want to drop everything else before sessions.

**Comment by pefoley2** [comment]
Take a look at http://redis.io/topics/lru-cache

**Comment by pefoley2** [comment]
https://github.com/tjcsl/ion/tree/redis should handle the lack of dropping sessions.
I'm not at all sure that it will properly garbage collect and/or cleanup invalid sessions though.

**Comment by pefoley2** [comment]
I'm not at all sure this is needed, and even if it is, i'll need to be well tested. Relevant diff is below:
diff --git a/intranet/settings/__init__.py b/intranet/settings/__init__.py
index 7e929e5..d973a6d 100644
--- a/intranet/settings/__init__.py
+++ b/intranet/settings/__init__.py
@@ -330,7 +330,8 @@ if not TESTING:
     SESSION_REDIS_DB = 0
     SESSION_REDIS_PREFIX = VIRTUAL_ENV + ":session"

-    SESSION_COOKIE_AGE = int(datetime.timedelta(hours=2).total_seconds())
+    # No TTL means redis doesn't evict sessions in low memory situations.
+    SESSION_COOKIE_AGE = None  # type: int
     SESSION_SAVE_EVERY_REQUEST = True

 CACHES = {

**Comment by ovkulkarni** [comment]
@pefoley2 do you know if this is still an issue?

**Comment by theo-o** [comment]
Haven't seen any redis problems. Closing.
