### ISSUE TITLE
The bottom bar could be a bit bigger...

### ISSUE THREAD

**Issue by ws04** [tjcsl/ion#373]
If it's so small it's hard to click the links, why have it in the first place?

**Comment by jwoglom** [comment]
On mobile? Or on desktop?

**Comment by ws04** [comment]
on desktop

**Comment by evanyeyeye** [comment]
what bottom bar?

**Comment by ws04** [comment]
the bar on the bottom of desktop ion

**Comment by fwilson42** [comment]
Could you take a screenshot of what you're referring to?

**Comment by ws04** [comment]
http://goo.gl/UCeK1U

**Comment by jwoglom** [comment]
We've received feedback from students and faculty that they want easy access to these links from the login page. To keep the page minimalist, they were placed at the bottom and kept at a small size. I don't particularly see a problem with the current setup; do you have any specific suggestions on what to change about this?

**Comment by ws04** [comment]
They just seem a bit too small to really use/notice

**Comment by evanyeyeye** [comment]
Right now, the layout of the login page is extremely clean. However, until he uploaded that screenshot I had never even noticed those links. With just a little bit of change to the font size and padding a lot more people will probably notice it with minimal effect on the nice appearance that you guys currently have. Maybe try changing the footer css block to the following:
```
.footer {
    position: fixed;
    bottom: 0;
    padding: 0 0 3px 6px;
    font-size: 13px;
    color: gray;
    z-index: 99;
    text-align: left;
    width: 100%;
    background: rgba(242,242,242,.5);
}
```

Differences: (click on images, fullscreen makes difference easier to see)

![before](https://cloud.githubusercontent.com/assets/14984764/13167563/42566574-d6a2-11e5-9909-7ebc47deaad2.png)

![after](https://cloud.githubusercontent.com/assets/14984764/13167562/4254f996-d6a2-11e5-8122-a106ab88da25.png)

It's a subtle difference, but it may be enough to give the footer more presence

**Comment by pefoley2** [comment]
Feel free to submit this change as a PR :)

**Comment by jwoglom** [comment]
PR merged
