### ISSUE TITLE
Using an HttpOnly CSRF cookie makes it more difficult for cross-site scripting attacks to steal the CSRF token.

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#375]
We need to audit ajax requests to prevent this change from breaking them.
https://docs.djangoproject.com/en/1.9/ref/settings/#std:setting-CSRF_COOKIE_HTTPONLY

**Comment by pefoley2** [comment]
Appears that https://github.com/tjcsl/ion/blob/master/intranet/static/js/common.js#L8 is the only place that needs updating.

**Comment by ezwang** [comment]
https://github.com/tjcsl/ion/blob/master/intranet/static/js/files.js#L24 will also need updating

**Comment by ovkulkarni** [comment]
is this still an issue?

**Comment by theo-o** [comment]
This does not appear to be an issue
