### ISSUE TITLE
Navigating to http://ion.tjhsst.edu/schedule doesn't work

### ISSUE THREAD

**Issue by ovkulkarni** [tjcsl/ion#378]
It shows a login page and then after logging in it shows [this](http://goo.gl/4bfw82) screen

**Comment by jwoglom** [comment]
This is the administrative page for managing bell schedules. Thus, the error page is intentional, as you don't have permissions to modify bell schedules. Where are you getting the link to /schedule?

**Comment by ovkulkarni** [comment]
I tried typing it in as a url. Also, I would recommend showing a 401 page rather than showing the login page again.

**Comment by pefoley2** [comment]
Back in the day, I was ticked as hell that the iodine "you don't have permissions" page was identical to the "page does not exist" one.
I'm with @ovkulkarni on having a 401 or some other obvious error.
