### ISSUE TITLE
Ion OAuth does not support Out of Band Applications

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#389]
Out of Band Applications use the URN `urn:ietf:wg:oauth:2.0:oob` as the Redirect URI in order to signify that the Application wants the user to give the Client Token to the Application manually.

Here is an example of how it looks using Google's API:

![](https://developers.google.com/accounts/images/installedresult.png)

**Comment by fwilson42** [comment]
This would be something that would need to be handled in upstream. I'm not actually sure if there's a use case for this in Ion, anyway, given as sessions die after a relatively short period of time due to Kerberos tickets expiring.

**Comment by jwoglom** [comment]
As this is an upstream issue with django-oauth-toolkit, and there does not seem to be a pressing need for this at this time, I am closing this bug.

**Comment by tcyrus** [comment]
See evonove/django-oauth-toolkit#235
