### ISSUE TITLE
Add function to delete files

### ISSUE THREAD

**Issue by ezwang** [tjcsl/ion#393]
There is no way to delete files or directories on the Files tab

Maybe just a simple X next to the file/folder?

**Comment by pefoley2** [comment]
Shouldn't be too hard to delete files, though there should be a confirmation dialog. Directories might be a bit more hairy.

**Comment by jwoglom** [comment]
There's another issue open to show last modified dates on folders and files, also. If we implement deletion, we would have to be very careful, and have a server-side confirmation, not through a confirm() box in javascript or anything like that.

**Comment by jwoglom** [comment]
Also, folder zipping has been requested multiple times

**Comment by jwoglom** [comment]
Done
