### ISSUE TITLE
Don't show room conflicts for out of building / admin activities in 8th office

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#394]
e.g. https://ion.tjhsst.edu/eighth/admin/rooms/sanity_check?block=3085
Should having multiple activities in the same room even be an error if the sum of their capacities is less then the total capacity of the room?

**Comment by jwoglom** [comment]
Usually there is only one activity in a room, so I would say yes. The sanity check isn't to see whether there is enough space in the room based on who is signed up, but rather where there are two activities booked in one room.
