### ISSUE TITLE
Don't display upload/delete if no permissions.

### ISSUE THREAD

**Issue by naitian** [tjcsl/ion#403]
If a user doesn't have the permissions to upload or delete a file to a filesystem, don't display the buttons.

**Comment by jwoglom** [comment]
Not sure if this can be tested for easily.

**Comment by pefoley2** [comment]
I mean, I assume pysftp can check permissions

**Comment by anonymoose2** [comment]
First, note that the LOCAL (Windows) domain is going away soon, so this would only be worth implementing for AFS.

The main roadblock with implementing this is that AFS doesn't respect normal Unix file permissions. To check if the user can access the filesystem, we'd have to run `fs listacl` and parse it manually. It would be messy, and if we parse it wrong then we might accidentally deny the user access to a directory they actually do have access to. In my opinion, it's best to err on the side of always showing the buttons and just letting the user discover that they can't modify anything.

This would be a nice feature, but it's low on the backlog and hacky/difficult to implement. Closing.
