### ISSUE TITLE
[feature] Info module, where longer-term announcements, guides, and other information can be posted

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#414]
Maybe style or think of it like a bulletin board?

**Comment by pefoley2** [comment]
If we do implement this, i'd like to suggest making it possible to dismiss news items :)

**Comment by Laur04** [comment]
I'm open to disagreement, but I believe this has been addressed. We have a useful links section for general long term guides, a more specific eighth period info module with more links and a "pinned" function for long term announcements. I think yet another place to look for information would be overwhelming and cluttered.
