### ISSUE TITLE
Rejected announcements don't show up properly

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#416]
e.g.
March 9, 2016, 11:42 a.m. - Lost Calculator -- requested by Cindy Powell, approved by Cindy Powell, rejected by None

**Comment by jwoglom** [comment]
How are they not shown properly?

**Comment by pefoley2** [comment]
It says approved by $name/None, and rejected by None, even though the announcement was rejected.
See https://ion.tjhsst.edu/announcements/admin_status

**Comment by jwoglom** [comment]
The "approved by" shows the teachers that approved it, if there were any. The rejected by shows the admin who rejected it; the issue here is that the admin who rejected it was not being saved, which is now resolved.
