### ISSUE TITLE
css 2.1 incompatibility

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#421]
Line 52 of intranet/static/css/emerg.css
https://www.codacy.com/app/tjcsl/ion/file/2296679569/issues/source?bid=3176160&fileBranchId=3176160
See http://stackoverflow.com/questions/11746581/nesting-media-rules-in-css
Are we requiring css 3.0 intentionally?

**Comment by jwoglom** [comment]
Was unintentional, resolved by switching to the AND syntax.
