### ISSUE TITLE
Clearing other_phone field throws error

### ISSUE THREAD

**Issue by ovkulkarni** [tjcsl/ion#441]
<img width="1280" alt="screenshot 2016-04-06 at 8 30 47 pm" src="https://cloud.githubusercontent.com/assets/16127719/14337359/16bb747c-fc3b-11e5-8e04-6f8c32fa0677.png">

**Comment by ovkulkarni** [comment]
A test was added for this in commit b2db772290438d9c44ad856c4b2e3f8cbbf63894

**Comment by pefoley2** [comment]
The test should fail until the bug is fixed, BTW

**Comment by ovkulkarni** [comment]
The bug seems to have disappeared
