### ISSUE TITLE
Filecenter cannot download files with an ampersand in the name

### ISSUE THREAD

**Issue by fwilson42** [tjcsl/ion#452]
Whenever someone tries to download a file with an ampersand in its name, the ampersand is added to the URL, like this:

`https://ion.tjhsst.edu/files/tj03_r?file=/R/GeoSystems/!!Stickler/Geology/Volcano%20Lab/Notes%20on%20Volcano%20Properties%20&%20Formation.doc`

The ampersand acts as a separator for GET parameters instead of acting as part of a filename. The result is that files with ampersands in the name can't be downloaded.

**Comment by pefoley2** [comment]
Sigh, looks like we need a bit more urlescape()
