### ISSUE TITLE
Themes should use SASS instead of CSS

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#466]

**Comment by sdamashek** [comment]
Why exactly? Why change it if it works?

**Comment by tcyrus** [comment]
Mainly to avoid confusion between the SCSS and CSS files

**Comment by anonymoose2** [comment]
The transition from CSS/SCSS to SASS ([yes, they are different](https://sass-lang.com/documentation/syntax)) never took place and is not currently planned. Closing.

**Comment by tcyrus** [comment]
Sorry, this ticket was misnamed. It was referring to the transition from CSS to SCSS/SASS, which was completed a while back.
