### ISSUE TITLE
Fix responsive width of "show more widgets" button

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#467]
Makes entire dashboard page break till after navbar when resized to small enough.

Has someone been messing with the css? I swear I've fixed this 1 or 2 times already. We're losing the css rule.

**Comment by pefoley2** [comment]
There's been a ton of refactoring stuff lately, yell at @tcyrus 
It's possible i screwed up a rebase at some point too.

**Comment by jamesthoughton** [comment]
I think I changed it with
https://github.com/tjcsl/ion/commit/d4878339d2dbc57e8a3f91d5caa29ff1a668d47f

**Comment by jamesthoughton** [comment]
That actually wasn't the commit that changed it -- I'll keep looking
