### ISSUE TITLE
Python warnings in cron scripts

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#488]
/usr/local/virtualenvs/ion/lib64/python3.4/imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
/usr/local/virtualenvs/ion/lib64/python3.4/importlib/_bootstrap.py:321: RemovedInDjango20Warning: Importing from django.core.urlresolvers is deprecated in favor of django.urls.
  return f(_args, *_kwds)

**Comment by pefoley2** [comment]
If they're caused by our code, we should fix them.
If it's someone else's code, just suppress it (see manage.py for examples)
