### ISSUE TITLE
Homeroom block bug

### ISSUE THREAD

**Issue by jamesthoughton** [tjcsl/ion#499]
Proposed behavior: switch the block label to "HR" but keep the "Homeroom block" above the selection menu

![homeroomblock](https://cloud.githubusercontent.com/assets/8053163/20820311/5b61a72a-b808-11e6-9ebf-ec7bd0138b01.PNG)

**Comment by jwoglom** [comment]
There's a javascript function that calculates the pixel width for the block-letter based on the number of characters it has -- i'd look there.

Also, sounds like the comments field on EighthBlock would be the place to put the "Homeroom Block" text.

**Comment by jamesthoughton** [comment]
![fixedwiththis](https://cloud.githubusercontent.com/assets/8053163/20913175/9789d3b0-bb43-11e6-9cd5-9043959bc36f.PNG)
