### ISSUE TITLE
Move Resources used by Ion out of Student Webdocs

### ISSUE THREAD

**Issue by tcyrus** [tjcsl/ion#505]
- https://www.tjhsst.edu/~2016jwoglom/ion-api-demo.html
- https://www.tjhsst.edu/~2016jwoglom/ionoauth/
- https://www.tjhsst.edu/~2016jwoglom/ion-memes/*
- https://www.tjhsst.edu/~2016jwoglom/uploads/tdfw.mp3?2
- https://www.tjhsst.edu/~2016jwoglom/uploads/tdfw.mp3?1
- https://tjhsst.edu/~2016jwoglom/canvastext?

**Comment by naitian** [comment]
Which of these are still relevant?

**Comment by jwoglom** [comment]
The first is a client side demo, which can go in /uploads; the second is a server side demo which probably has to stay (I think it's PHP). 

The memes were only relevant to one April fool's day application, and URLs of the posts were hard coded into the database entry for each post in the board application which used them. But they can be put in static if you want just for historical preservation.

I think the, um, special audio file is already moved locally.

Canvastext is probably not relevant (2017 graduates can decide if they want to put a similarly flashy "2017" logo on the login page near the end of school).
