### ISSUE TITLE
Dynamically handle aspect ratio change for user pictures

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#506]
Photos changed from ~4:5 (172x228px) to 3:4 (240x320px). Photo container is still exactly 5:4 (172x215px), which means that old photos appear semi-distorted and new photos appear extremely distorted. The application should automatically show the picture in the correct aspect ratio, and not be hardcoded for a specific resolution (CSS/img width=172px, with auto height perhaps?).

The default picture icon (static/img/default_profile_pic.png) might also have to be remade for the new resolution(s), although this probably isn't necessary.

**Comment by ovkulkarni** [comment]
No longer an issue
