### ISSUE TITLE
Sending POST requests to the API using OAuth doesn't work

### ISSUE THREAD

**Issue by spenceratkin** [tjcsl/ion#516]
Whenever a POST request is sent to the API, for example to `https://ion.tjhsst.edu/api/signups/user`, the request fails and the following error is returned: 
```
{
  "detail" : "CSRF Failed: Referer checking failed - no Referer."
}
```
This behavior only occurs when authenticating through OAuth and when sending POST requests.  POST requests work when using HTTP basic auth, and performing GET requests on OAuth also works fine.

**Comment by ezwang** [comment]
This should be fixed now.
