### ISSUE TITLE
/api/blocks/<pk> not working with client credentials (c'mon guys, not again)

### ISSUE THREAD

**Issue by jediguy13** [tjcsl/ion#530]
See https://github.com/tjcsl/ion/issues/529, https://github.com/tjcsl/ion/issues/524.

I know it's hard, but could someone at least test the next fixing commit to make sure it works? Each time this is fixed, it breaks in another place.

**Comment by ovkulkarni** [comment]
there is a test for this, and it gets run on every commit to make sure it will work. Not sure what the issue is this time.

**Comment by ezwang** [comment]
It looks like this was broken during the no-ldap changes, the reason it wasn't caught by the test is that the response returned 200 and displays:
```
{'details': ['Unknown error occurred.']}
```
The test only checks for a 200 response. I'll fix the error and update the test.

**Comment by jediguy13** [comment]
Something else to add: I am getting non error responses for 8th periods added after the no-leap changes, so the issue is not too applicable anymore. But yeah, changing the test is a good idea. Thanks for looking into this @ezwang!
