### ISSUE TITLE
Implement dynamic groups, and merge class groups into them

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#55]
Dynamic groups would be able to be created based on certain criteria, like in Iodine. If that is implemented, then class groups could just be a subset of those with "user.grade=[9-12]".

**Comment by ethanal** [comment]
In iodine, aren't dynamic groups used just for classes? True dynamic groups would significantly complicate and slow down any group membership query.

**Comment by jwoglom** [comment]
They're used for classes, gender, and all student/faculty groups.

**Comment by ethanal** [comment]
News posts are never targeted to staff and I don't recall them ever being targeted towards a specific sex. I think it's just too much overhead for a very rare situation. Groups based on only class or staff can be done in sql but everything else requires 1 ldap query per student.
