### ISSUE TITLE
Upgrade to Django Channels 2

### ISSUE THREAD

**Issue by naitian** [tjcsl/ion#554]
This involves some refactoring, because Channels 2 is not backwards-compatible with Channels 1.

https://channels.readthedocs.io/en/latest/one-to-two.html#how-to-upgrade

That said, from what I've read, I don't think we need to change that much.

**Comment by duvallj** [comment]
Files w/ direct dependencies on channels (found using `grep -r channels intranet/*`):
```
intranet/app/bus/consumers.py
intranet/asgi.py
intranet/routing.py
intranet/collected_static/channels/js/websocketbridge.js
```
