### ISSUE TITLE
Improve Session Management

### ISSUE THREAD

**Issue by naitian** [tjcsl/ion#559]
The suggestion has been made multiple times to increase the length of sessions beyond 2 hours. I think that's both reasonable and useful, but of course this opens up security concerns.

I think a good compromise would be to extend session lifetime, but also implement a session management view where logged-in users can remove sessions that they are no longer using. This model is used by a lot of services including GitHub, Facebook, etc to offer more or less infinite-length sessions.

![image](https://user-images.githubusercontent.com/3933321/39163014-85470444-4746-11e8-9115-c651f483ad42.png)

**Comment by theo-o** [comment]
+1 for a session management view.
I think a better approach for session management would be a `Trust this device` checkbox. This way, end users can select which devices they trust to be logged in longer (lets say 30 days).  Users would still be able to revoke their session later in the session management view.
