### ISSUE TITLE
Identify calculator's owner using serial number feature deprecated?

### ISSUE THREAD

**Issue by liamrathke** [tjcsl/ion#563]
I just found a calculator, and I wanted to return it to the original owner. When I was a freshman, I remember entering my own calculator's serial number into Iodine. However, I wasn't able to find that link/widget when logging in to Ion today. 

Is this feature just not part of the intranet anymore, or am I looking in the wrong place?

**Comment by ezwang** [comment]
It should still exist under [https://ion.tjhsst.edu/lostfound/](https://ion.tjhsst.edu/lostfound/). You can navigate to it using the menu shown by clicking your name in the upper right corner. I don't think that students are able to access other people's calculator serial numbers, but staff members should have access.

**Comment by liamrathke** [comment]
Thanks!

I tried submitting but I got an HTTP 5000 error :/
<img width="572" alt="screen shot 2018-05-24 at 8 43 22 am" src="https://user-images.githubusercontent.com/33555592/40486219-a9f125a4-5f2e-11e8-9f67-6562be64db32.png">

Is there a staff member I should contact instead?

**Comment by naitian** [comment]
You might find greater success giving the calculator to the security office.
