### ISSUE TITLE
List Out-of-County Buses on Signage

### ISSUE THREAD

**Issue by naitian** [tjcsl/ion#568]
I think we should put it beneath the "school has not ended yet" box.

![image](https://user-images.githubusercontent.com/3933321/40878737-39fec80a-6663-11e8-8382-2940acba058f.png)

**Comment by DylanJones** [comment]
Someone fixed this a few weeks ago

**Comment by DylanJones** [comment]
Whoops, apparently we still need more busses but somehow the incomplete changes were merged into master
https://tjcsl.slack.com/files/U3U685SAC/FFDMTRWRL/bus.png
