### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ethanal** [tjcsl/ion#58]
Don't start this until everything else works
At one point python-ldap was the only thing preventing us from moving to python 3
This may help with that https://pypi.python.org/pypi/ldap3

**Comment by pefoley2** [comment]
I'm taking a crack at some of this on the python3 branch.

**Comment by pefoley2** [comment]
Looks like we'll also need to move from fabric to it's successor https://github.com/pyinvoke/invoke which has python3 support.

**Comment by pefoley2** [comment]
It appears that ldap3 doesn't not yet support gssapi, see cannatag/ldap3#33

**Comment by pefoley2** [comment]
django-debug-toolbar-line-profiler is also python2-exclusive.

**Comment by pefoley2** [comment]
This is mostly working on the python3 branch, and should be integrated at some point after launch

**Comment by jwoglom** [comment]
Ion now uses Python 3.
