### ISSUE TITLE
Move from python-ldap to ldap3

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#59]
https://pypi.python.org/pypi/ldap3

Should be fairly simple, except for the lack of gssapi support, see cannatag/ldap3#33
https://github.com/pythongssapi/python-gssapi may be helpful in implementing this.

**Comment by pefoley2** [comment]
Working on python3 branch, blocked on upstream changes and ssl cert for iodine-ldap.

**Comment by jwoglom** [comment]
Done. Thanks pfoley.
