### ISSUE TITLE
Move from fabric to a python3 compatible alternative.

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#60]
Fabric doesn't support python3, so we'll need to move to its successor, https://github.com/pyinvoke/invoke

**Comment by pefoley2** [comment]
I've been poking around with invoke, and it seems like it isn't really suitable at this point.
https://pypi.python.org/pypi/Paver/ might be a good alternative.

**Comment by pefoley2** [comment]
I poked paver as well, and it seems like the best approach is to just install fabric for python2 and use that instead.

**Comment by jwoglom** [comment]
Fabric3 is now used as a Python3 compatible fork.
https://pypi.python.org/pypi/Fabric3
