### ISSUE TITLE
Introduce mandatory announcements

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#601]
Allow users to request announcements that must be broadcast to the entire school, regardless of preference in settings.  This will likely be restricted to admin, and confirmation via a dialog by an announcements admin should be received before being accepted.

**Comment by anonymoose2** [comment]
The basic functionality for this already exists (`Announcement.notify_email_all`). It was disabled without explanation in 6c9b05e9d94 by commenting out the relevant lines in `intranet/apps/announcements/forms.py`.
