### ISSUE TITLE
Remove or replace django-debug-toolbar-line-profiler

### ISSUE THREAD

**Issue by pefoley2** [tjcsl/ion#61]
django-debug-toolbar-line-profiler is python2 exclusive, so we will either need to remove it or find a replacement.

**Comment by pefoley2** [comment]
As this doesn't support python3, we should probably just remove it from the repo.

**Comment by jwoglom** [comment]
Has this been done?

**Comment by pefoley2** [comment]
It is currently disabled, iirc
I wasn't sure if it was worth keeping or not.
