### ISSUE TITLE
Consider requiring Python 3.6+

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#675]
In the process of attempting to upgrade to Django Channels 2 (#554), I have been blocked by https://github.com/django/channels_redis/issues/145#issuecomment-449744857 as `channels_redis` has dropped support for Python 3.5 due to buggy async support.

We should consider dropping Python 3.5 support (requiring changes to the test matrix and dev VMs to become bionic). Thoughts, @anonymoose2?

**Comment by anonymoose2** [comment]
I propose a series of steps to introduce this change:
1. One Ion developer should upgrade their development VM to `bionic` and test with Python 3.6. I don't see any reason why it should break anything, but you can never be too careful.
2. This change should be committed and pushed to `master`. Other developers can test and make sure their environments work too.
3. The Travis CI build should be switched to `bionic` and have the Python 3.5 build removed.
4. Following a full backup (or VM snapshot), the production Ion sever should be upgraded to `bionic` (but still running Python 3.5).
5. If, after a few weeks, Ion has not experienced any significant issues as a result of the upgrade, we can switch it to Python 3.6.
6. If, after a few weeks, Ion still has not experienced any issues, we can introduce a hard Python 3.6 requirement and begin adding features that break Python 3.5 support.

**Comment by theo-o** [comment]
Makes sense.  I am working on changes to the `Vagrantfile` right now.

**Comment by theo-o** [comment]
Resolved by #676 and 3.6.8 running in production. Closing.
