### ISSUE TITLE
Add advanced group creation page

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#704]
Although admins have a quick way to create groups with basic properties on the dashboard, it may be useful for admins to quickly add users to a group upon creation (so that they do not have to visit the edit group page after creating the group).

The page would allow the admins to a add a provided list of users to the newly-created group as well as set its name. It may make sense to reuse the same template/structure as the edit group page.

**Comment by Laur04** [comment]
This seems redundant, as the `Add` button for groups already redirects to the `Edit` page where admins can add users. Any attempt to rework this to include both creating the group and adding users on the same page would either require one to submit the group name first so the object could be created (essentially replicating current behavior) or re-writing not only `add_group_view` but also `eighth_admin_upload_group_members` and `eighth_admin_add_member_to_group` to work independently of `group.id` In terms of the number of clicks, the proposed process is identical the current one. I'm hesitant to re-work code in what seems to me to be a harder to follow manner for little to no UX benefit. I'm happy to reopen this if anyone has valid counter points though.
