### ISSUE TITLE
docs: Reorg coding style docs

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#720]
https://tjcsl.github.io/ion/developing/styleguide.html

and improve formatting

**Comment by anonymoose2** [comment]
Was this was fixed in 088ad266598dccdafb49ea956f275e9b62a4b28a, or are more changes needed?

**Comment by theo-o** [comment]
A few more changes are needed like how you can use `isort` to comply with import sorting, converting the main points section into an actual section with a heading, and some sort of separation between the imports and the good types of imports.
