### ISSUE TITLE
Agree on an ordering for imports

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#739]
As discussed in https://github.com/tjcsl/ion/pull/738#discussion_r310305166, we have a disagreement over how to properly order imports.

This issue is meant to collect opinions on the different sides. What we can agree on is that we should split up our imports into related blocks and order the imports alphabetically within in the block.  The main question at issue is how the third-party and Django imports should be ordered in general.

P.S.: We should probably enforce whatever we agree on in CI.

/cc @anonymoose2

**Comment by theo-o** [comment]
@anonymoose2: From my perspective, I think stdlib -> third-party -> Django -> local imports makes the most sense because I see Django as its own distinct category of third-party libraries. I personally think that Django is closer to Ion because it itself uses third-party libraries and standard libraries, although I do see where your line of thinking comes from.

I am also somewhat inspired by [Django's style guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#imports) (which I guess is sort of in a position of authority):
>Put imports in these groups: future, standard library, third-party libraries, other Django components, local Django component, try/excepts.

#### Unrelated thought on CI
I also think that this is a good CI step:
```bash
isort -c $(find intranet -name \*.py ! -path \*migrations\*)
```

**Comment by anonymoose2** [comment]
Okay, you have me with the Django style guide. That's authoritative enough for me.

With regards to CI, that sounds good. I'm working on a cleanup/fixes PR, and I can reorder the imports and add the check as part of that. I'll close the issue when it gets merged.
