### ISSUE TITLE
Use cStringIO in Python 2

### ISSUE THREAD

**Issue by ethanal** [tjcsl/ion#76]
https://github.com/tjcsl/ion/blob/7fafddfd90dce1681d0d4c7f06a45ae62955125e/intranet/apps/eighth/views/attendance.py#L5

**Comment by pefoley2** [comment]
from six.moves import cStringIO should do it.

**Comment by ethanal** [comment]
It should be BytesIO in python 3 though so catching the ImportError is probably the only way

**Comment by pefoley2** [comment]
point.

**Comment by pefoley2** [comment]
That should do it, feel free to cherry-pick to master.
