### ISSUE TITLE
Dropdown boxes do not have dark mode applied

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#760]
For example, the `select` element on https://ion.tjhsst.edu/eighth/activity/statistics/925.

**Comment by theo-o** [comment]
I seem to only experience this behavior on Firefox.

**Comment by anonymoose2** [comment]
This is a Firefox-specific bug. [A report was filed](https://support.mozilla.org/en-US/questions/1141257), but no action has been taken on it in 2 years. A DuckDuckGo search shows dozens of people having the same issue, but there appears to be no good solution. Closing.

**Comment by theo-o** [comment]
For future people, setting `dom.forms.select.customstyling` to `true` (and restarting the browser) resolves the issue.
