### ISSUE TITLE
Consider whether to add the Referrer Policy header

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#770]
## Topic of discussion
See https://scotthelme.co.uk/a-new-security-header-referrer-policy/ for a quick overview.  The `Referrer-Policy` header allows us to control what sort of URLs should be passed along when referring to other sites.

## Proposed options/solutions
These are the acceptable headers:
* "no-referrer",
* "no-referrer-when-downgrade",
* "same-origin",
* "origin",
* "strict-origin"
* "origin-when-cross-origin",
* "strict-origin-when-cross-origin",
* "unsafe-url"

This middleware should do the trick: https://github.com/ubernostrum/django-referrer-policy

## Personal opinion (if applicable)
Since our URLs do not contain secret or sensitive content (our URLs are basically IDs with actions), it doesn't make sense to eliminate adding a referrer completely or hide our URLs.  However, I don't think we should be passing a referrer when we are downgrading from HTTPS to HTTP which is why I think `no-referrer-when-downgrade` makes the most sense for our usecase.

**Comment by anonymoose2** [comment]
I would personally favor `strict-origin-when-cross-origin` (only sends the origin on cross-origin requests; doesn't send anything on downgrades). I just don't think there's any need to send the full URL to other sites when it's not much use to them anyway (as @theo-o mentioned, the URLs are just IDs with actions).

**Comment by theo-o** [comment]
That sounds fair enough.
