### ISSUE TITLE
Add a logout button next to nav dropdown

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#772]
## Feature description
Adding a logout button (either the power button icon or arrow pointing out icon would work) to the left of the navbar that when clicked logs a user out.

## Rationale for adding feature
Currently, it takes two clicks to logout from Ion, and we should be making it easy for students to be secure and protect their Ion sessions.  Eliminating an extra click would do so and would not be a major disruption to our nav UI.

## Suggested implementation(s) (if applicable)
-

**Comment by jatinAroraGit** [comment]
Hey there , I can work on this issue.

**Comment by theo-o** [comment]
> Hey there , I can work on this issue.

Hi @jatinAroraGit, thank you for your interest in contributing to Ion.  Ion is an internal application that we have made open source. Due to program constraints, we are unable to accept pull requests from persons not part of the TJ community.
