### ISSUE TITLE
Dark mode is inconsistent in bolding between polls and events

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#777]
## Steps to reproduce
1. Make sure there are no upcoming events scheduled
2. Make sure there are no polls open
3. Visit https://ion.tjhsst.edu/events in dark mode
4. Visit https://ion.tjhsst.edu/polls in dark mode
5. Look at the text `There are no events to display at this time. ` and compare it with the same text in polls

## Expected behavior
The text `There are no polls to display at this time. ` is bolded to match the behavior for a similar situation for polls.

## Actual behavior
The text is not bolded.

**Comment by anonymoose2** [comment]
TL;DR: Bolding the text was a deliberate design decision. I probably would have bolded the polls text too if I'd thought about it.

White text on a black background doesn't have quite as great contrast as black text on a white background. To try to compensate in certain cases (here, in the username/password fields on the login screen, or in the search bar), I bolded text to make it stand out. This was supposed to be a feature, not a bug.

I can either 1) un-bold the text if you still don't think it needs to be bolded or 2) bold the polls text for consistency. Which would you prefer?

**Comment by theo-o** [comment]
I think bolding is a reasonable UI decision, so I am leaning towards consistency.
