### ISSUE TITLE
Polls should not be displayed in Django admin

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#779]
## Feature description
Remove the polls section from Django admin.

## Rationale for adding feature
The questions and responses to polls should not be editable/viewable by any person via the Ion  Django admin web interface to preserve the integrity of polls.  The only exception should be directly via the DB/Django shell in rare circumstances where a bug has been introduced, etc.

## Suggested implementation(s) (if applicable)
-

**Comment by anonymoose2** [comment]
Does this close #672?

**Comment by theo-o** [comment]
> Does this close #672?

Yes
