### ISSUE TITLE
Groups field should be disabled in events request view when not groups admin

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#782]
## Feature description
When the requesting user is not a groups admin, they should not be able to change the "Group" field in the event request form at https://ion.tjhsst.edu/events/request.

## Rationale for adding feature
Since the requesting user cannot view any of the groups in this event request, we should just disable the field so that they are aware that they cannot change it and that the requested event is set to be shown to everyone.

## Suggested implementation(s) (if applicable)
-

**Comment by anonymoose2** [comment]
It appears that the `GroupProperties` class has a `student_visible` attribute, and non-group admins *are* allowed to set the group field to any group that has that attribute set to `True`.

Would it perhaps be better to disable the field if there are no student-visible groups?

**Comment by theo-o** [comment]
> It appears that the `GroupProperties` class has a `student_visible` attribute, and non-group admins _are_ allowed to set the group field to any group that has that attribute set to `True`.
> 
> Would it perhaps be better to disable the field if there are no student-visible groups?

Yes
