### ISSUE TITLE
Await django-formtools release that supports Django 2.2

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#802]
The [latest release](https://github.com/django/django-formtools/releases/tag/2.1) of django-formtools was v2.1 in Oct 2017. Testing for Django 2.2 was added in https://github.com/django/django-formtools/commit/25cc7a50b22d1d361de5f159c514de6d82eeec9b (Jan 2019), but there has not been a release since then.

Blocks #800

**Comment by anonymoose2** [comment]
[Version 2.2](https://github.com/jazzband/django-formtools/releases/tag/2.2) (released 9 days ago) adds support for Django 2.2 ([changelog](https://github.com/jazzband/django-formtools/blob/2.2/docs/changelog.rst)).
