### ISSUE TITLE
Switching to ion dark mode based on iOS/macOS system settings

### ISSUE THREAD

**Issue by sparthaje** [tjcsl/ion#821]
## Feature description
When the system dark mode is turned on (on iOS and macOS) it should switch ion to dark mode. When its turned off, it should turn off ion's dark mode. 

It should be an optional feature though. 

## Rationale for adding feature
iOS 13+ and macOS Mojave + support this feature and it would be nice if ion works with the user's system settings. 

## Suggested implementation(s) (if applicable)
There is a css media rule that activates when the system dark mode is turned on:

    @media (prefers-color-scheme: dark) {
        // all ion dark mode css
    }

**Comment by anonymoose2** [comment]
This would be a great feature. Unfortunately, due to the way dark mode is currently handled and the way this would need to be implemented, this is not feasible right now. Closing.
