### ISSUE TITLE
Bug in `pylint-plugin-utils`

### ISSUE THREAD

**Issue by anonymoose2** [tjcsl/ion#829]
## Steps to reproduce
1. Run `pylint --jobs=0 --disable=fixme,broad-except,global-statement,attribute-defined-outside-init intranet/` (copied from the Travis build) in a Vagrant development environment.

## Expected behavior
Pylint should run and exit correctly.

## Actual behavior
Pylint fails with the error (full traceback omitted for clarity):
`ImportError: cannot import name 'UnknownMessageError' from 'pylint.utils'`

This is an upstream bug. [An issue tracking it](https://github.com/PyCQA/pylint-plugin-utils/issues/15) and [a PR fixing it](https://github.com/PyCQA/pylint-plugin-utils/pull/16) have been opened, but the maintainers have not yet responded to either.

## Possible courses of action:
1. Temporarily install `pylint==2.3.1` in the Travis build until this issue has been fixed upstream.
2. Wait for the fix to be implemented, accepting that until then the build will fail and we won't get any warnings from Pylint.

Pinging @theo-o for thoughts.

**Comment by theo-o** [comment]
I believe that downgrading to the latest working version and then waiting for an upstream fix is the best fix.
