### ISSUE TITLE
Consider adjusting defaults for email notifications

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#834]
## Topic of discussion
Currently, students need to opt-in to receive emails . We may want to change this structure.

## Proposed options/solutions
* Keep the status quo
* For new students, make receiving eighth emails by default on.
* For new students, make receiving eighth period and news emails by default on
* For new students, make receiving emails of all types by default on
* Prompt all students to select their notification preferences during the welcome process (keep all boxes checked by default on)

## Personal opinion (if applicable)
I am personally leaning for the eighth email/news emails to be default on or to prompt students to set notification preferences during the welcome process. I think it is useful for students to get important news in their inbox since students should be aware.  If they don't want to receive them, they can just opt out (in preferences or, if we choose the latter option, during the welcome process).

**Comment by anonymoose2** [comment]
I am personally in favor of 1) making eighth/news emails default to on for new students and 2) leaving current students alone (no changes, no form on the welcome popup at the start of the next year).

I agree students should be getting important news, but prompting during the welcome process has some difficulties:
- Most students probably just click through the screens. If we require them to submit the form to advance, some of them might just click "Next" and accidentally change their settings without realizing it.
- If we make the form optional, realistically speaking, nobody will fill it out. Again, most people probably just click through the screens, and they'll most likely completely miss the form.

I think it's best to just keep all current students as-is and apply the fix going forward

**Comment by theo-o** [comment]
Your plan and reasoning sounds reasonable.

I would just note (for any future implementer) that it would probably be a good idea to mention during the welcome process that these settings are being set (for new students) as on and that they can disable sending those emails in preferences.
