### ISSUE TITLE
Change reauthentication implementation to avoid security issues when session management page is added

### ISSUE THREAD

**Issue by anonymoose2** [tjcsl/ion#846]
## Topic of discussion
Currently, when the user is required to re-authenticate to Ion to perform certain maintenance tasks, the `reauthenticated` session key is set to `True`. This then enables users to view pages that require reauthentication until their session expires.

The problem is that the session management page proposed in #559/#771 and implemented in #839 would reduce the security of this reauthentication method, since users would be able to perform these maintenance tasks on any of their trusted devices for several days after having reauthenticated only once. We should fix this so users have to re-authenticate every few hours, at least.

## Proposed options/solutions
*First, whatever the re-authenticate expiration timeout is and however it is implemented, it should be defined in `settings/__init__.py`. so it can be changed easily.*

1. Instead of setting the `reauthenticated` key, set a `reauthenticated_at` (or similar) key to the current time (probably just `time.time()` for simplicity). The `reauthentication_required` decorator can then check if the amount of time that has elapsed since this was set is less than the expiration timeout.
2. Set a separate cookie with the current time. The problem here is that we would need to do a number of things in order to properly secure it -- like signing the cookie so we know it's from a trusted source -- and at that point we're almost reimplementing Django sessions.

We also need to decide on whether or not this should auto-renew every time the user visits Ion once they have re-authenticated.

## Personal opinion (if applicable)
I am in favor of simply setting a different field in the session. I also think that auto-renewing this every time the user visits Ion would introduce additional security issues, so we should just set it once when they re-authenticate.

**Comment by theo-o** [comment]
Although I do see the immense security benefits for option 2 (signing a cookie), I am personally leaning towards option 1 because the primary goal of `reauthentication_required` should be to confirm that a user really wants to escalate their privileges to the maximum possible, instead of 

If a user's session (especially an eighth admin's account) is compromised, they already can wreck havoc without going to parts of that are wrapped with `reauthentication_required`.
