### ISSUE TITLE
Django wizards don't work well with browser history, and require going back to the first step

### ISSUE THREAD

**Issue by jwoglom** [tjcsl/ion#86]
If the input text box is selected then this process works perfectly, whether I then search for an item or just select one. However, if it is not, then after hitting "Next" the block must be selected again, and the error "this field is required" appears.

**Comment by ethanal** [comment]
Can you clarify on irc?

**Comment by ethanal** [comment]
Replicate by submitting activity form using enter key or form submit button on mobile

**Comment by jwoglom** [comment]
Use of wizards has been reduced, and wizards redirect to pages that display information when needed to prevent breakage when refreshed
