### ISSUE TITLE
Switch to a custom Application model for OAuth applications

### ISSUE THREAD

**Issue by anonymoose2** [tjcsl/ion#873]
## What needs to be refactored
Switch to a custom `Application` model for OAuth applications.

This will require creation of a data migration to convert all the current `Application`s to custom ones. In addition, database backups should be performed immediately before deployment of this feature in order to minimize the chances of data loss, and tests should be conducted immediately following its deployment.

## Rationale
This would allow implementation of #786, as well as validation of other aspects of `Application`s.

**Comment by anonymoose2** [comment]
Based on further research into the `django-oauth-tooklit` module and some discussion with @abagali1, I do not believe this is possible. Instead, I would like to propose adding a custom model that has a `OneToOneField` pointing to the `Application` and stores CSL-specific data.

That would make things like #786 and #878 trickier, but perhaps we could overwrite the `django-oauth-toolkit` views/forms using something like [this](https://stackoverflow.com/a/54693912/6876037) and add our own custom validation.

@theo-o thoughts?

**Comment by Laur04** [comment]
What CSL specific information (besides forcing a name) are we looking to store?

**Comment by anonymoose2** [comment]
> What CSL specific information (besides forcing a name) are we looking to store?

See #878. Also, there may be a need to store information in the future.
