### ISSUE TITLE
Add Morning Bus Arrival Page

### ISSUE THREAD

**Issue by keegan** [tjcsl/ion#954]
## Feature description
A page where bus admins can log the arrival of buses in the morning.  They should be able to select a route and mark that it has arrived. 

## Rationale for adding feature
This would simplify tracking buses for attendance and security purposes in the morning.

## Suggested implementation(s) (if applicable)
- Create a new timestamp model in the bus app
  - Each timestamp should have a foreign key to a bus route
- Make a new page where admins can mark buses as arrived and non-admins can view a list route statuses
  - each route should display as arrived or not, and if arrived show the time it arrived
 - /bus should route between the current bus location page and the bus arrival page depending on time of day (arrival before noon, location after noon)

**Comment by Laur04** [comment]
I'm working on this, can you assign it to me?
