### ISSUE TITLE
eighthOffice Login Issue - Ask Andrew

### ISSUE THREAD

**Issue by ethanal** [tjcsl/ion#98]

**Comment by jwoglom** [comment]
Needs to use a simple LDAP bind -- eighthOffice is not in kerberos.

**Comment by ethanal** [comment]
What is the password checked against?

**Comment by pefoley2** [comment]
Shouldn't you be able to do a default username/pass ldap bind like for auth user?

**Comment by ethanal** [comment]
Oh simple bind with the ``eighthOffice`` account not ``authuser`` I see.

**Comment by ethanal** [comment]
Do any other accounts need a simple bind or can there just be a special case for ``eighthOffice``?

**Comment by pefoley2** [comment]
Are you planning to implement master password?

**Comment by ethanal** [comment]
Master password is already implemented https://github.com/tjcsl/ion/blob/master/intranet/apps/auth/backends.py#L116-L166

**Comment by pefoley2** [comment]
Ok, I'd check w/ @ahamilto but I don't think anything other than authuser/eighthOffice should need a simple bind.

**Comment by fwilson42** [comment]
According to @ahamilto the purpose of using an LDAP simple bind is to allow eighthoffice to still log in if Kerberos infrastructure is down (historically Kerberos KDCs ran on machines with other things as well, so they were not nearly as stable), so there should *not* be any other users that need an LDAP bind for authentication

**Comment by ahamilto** [comment]
I can do a query when i get home to check for any others. I think there
might be some stembassadors accounts that use ldap binds.

**Comment by jwoglom** [comment]
This has been fixed, eighthoffice is now a Kerberos account. Will open another issue for future reference to keep the possibility of adding this open.
